import { AvatarAction, CharacterSprites } from "@/types/avatar";

const rain: CharacterSprites = {
  attack: {
    image: require("@assets/sprites/rain/attack.png"),
    columns: 3,
    rows: 10,
    width: 198,
    height: 165,
    frameCount: 28,
    frameDuration: 10,
  },
  run: {
    image: require("@assets/sprites/rain/move.png"),
    columns: 1,
    rows: 1,
    width: 98,
    height: 67,
    frameCount: 1,
    frameDuration: 10,
  },
  idle: {
    image: require("@assets/sprites/rain/idle.png"),
    columns: 3,
    rows: 2,
    width: 72,
    height: 76,
    frameCount: 4,
    frameDuration: 10,
  },
  roll: {
    image: require("@assets/sprites/rain/move.png"),
    columns: 1,
    rows: 1,
    width: 98,
    height: 67,
    frameCount: 1,
    frameDuration: 10,
  },
  hit: {
    image: require("@assets/sprites/rain/idle.png"),
    columns: 3,
    rows: 2,
    width: 72,
    height: 76,
    frameCount: 4,
    frameDuration: 10,
  },
  dying: {
    image: require("@assets/sprites/rain/dying.png"),
    columns: 1,
    rows: 1,
    width: 69,
    height: 66,
    frameCount: 1,
    frameDuration: 10,
  },
  dead: {
    image: require("@assets/sprites/rain/dead.png"),
    columns: 1,
    rows: 1,
    width: 87,
    height: 64,
    frameCount: 1,
    frameDuration: 10,
  },
  winBefore: {
    // 402x1048
    image: require("@assets/sprites/rain/win_before.png"),
    columns: 3,
    rows: 8,
    width: 134,
    height: 131,
    frameCount: 22,
    frameDuration: 10,
  },
  win: {
    image: require("@assets/sprites/rain/win.png"),
    columns: 3,
    rows: 2,
    width: 93,
    height: 94,
    frameCount: 4,
    frameDuration: 10,
  },
  walk: {
    image: require("@assets/sprites/rain/move.png"),
    columns: 1,
    rows: 1,
    width: 98,
    height: 67,
    frameCount: 1,
    frameDuration: 10,
  },
  critical: {
    image: require("@assets/sprites/rain/attack.png"),
    columns: 3,
    rows: 10,
    width: 198,
    height: 165,
    frameCount: 28,
    frameDuration: 10,
  },
};

export default rain;
